Comicsbook/Controllers/CalendarController.cs
using System.Linq;
using System.Web.Mvc;
using Comicsbook.Models;
using System.Collections.Generic;

namespace Comicsbook.Controllers
{
    [HandleError()]
    public class CalendarController : Controller
    {
        ApplicationDbContext applicationContext = new ApplicationDbContext();

        // GET: Calendar
        public ActionResult ShowInitialCalendar()
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            ApplicationUser currentUser = applicationContext.Users.First(user => user.UserName == User.Identity.Name);
            ViewData["User"] = currentUser;
            ViewBag.CurrentUser = currentUser;
            ViewBag.NeedSidebar = true;
            return View();
        }

        [HttpPost]
        public ActionResult ShowPartialCalendar(int month, int year)
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            ApplicationUser currentUser = applicationContext.Users.First(user => user.UserName == User.Identity.Name);
            ViewData["User"] = currentUser;
            ViewData["Month"] = month;
            ViewData["Year"] = year;
            return PartialView("CalendarPartial");
        }

        public Dictionary<string, int> GetTagsCloudBlock(int maxTags = 20)
        {
            Dictionary<string, int> result = new Dictionary<string, int>();
            // Counts number of tags added (we only need max of %maxTags% tags).
            int count = 0;
            int total = maxTags < applicationContext.Tags.Count() ? maxTags : applicationContext.Tags.Count();
            ViewBag.Links = new Dictionary<string, int>();
            foreach (var tag in applicationContext.Tags
                        .OrderByDescending(x => x.ContentTags.Count))
            {
                result.Add(tag.Word, count * 5 / (total));
                ViewBag.Links.Add(tag.Word, tag.Id);
                ++count;
                if (count >= maxTags)
                    break;
            }
            return result;
        }
    }
}

Comicsbook/Controllers/FeedController.cs
using Comicsbook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Comicsbook.Controllers
{
    [HandleError()]
    public class FeedController : Controller
    {
        ApplicationDbContext applicationContext = new ApplicationDbContext();
        // GET: Feed

        [Authorize]
        public ActionResult Feed(int page = 1)
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();

            List<UserTextContent> allContents = applicationContext.Contents.ToList();
            List<UserTextContent> feedContents = new List<UserTextContent>();
            var users = applicationContext.Users;
            var user = users.First(x => x.UserName == User.Identity.Name);

            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUser = user;
            }

            ViewBag.NeedSidebar = true;

            // Если у юзера не добавлено ни одного тега, не выводим ему статьи.
            if (user.SubscribedTags.Count == 0)
            {
                allContents.Clear();
            }

            var subscribed = user.SubscribedTags.Select(st => st.TagId);
            
            feedContents.AddRange(allContents
                .Where(
                    c => subscribed.Intersect(c.Tags.Select(t => t.TagId)).Count() > 0
                        || applicationContext.SubscribedUsers.Any(su => su.SubscribedAuthorId == c.AuthorId
                            && su.SubscriberId == user.Id)));

            var ignored = user.IgnoredTags.Select(it => it.TagId);
            feedContents.RemoveAll(c => ignored.Intersect(c.Tags.Select(ct => ct.TagId)).Count() > 0);

            // Проверим, что статьи содержат теги, на которые пользователь подписан, и не содержат те, которые он игнорирует.
            // Между проверками добавим все статьи пользователей, у которых данный находится в подписчиках.
            //foreach (var tag in user.SubscribedTags)
            //{
            //    allContents = allContents
            //            .Where(article => article.Tags
            //                .Any(articleTag => articleTag.TagId == tag.TagId))
            //                    .ToList();
            //}

            //var query = from subscription 
            //            in applicationContext.SubscribedUsers 
            //            where subscription.SubscriberId == user.Id
            //            select subscription;
            
            //foreach (var subscribtion in query)
            //{
            //    foreach (var article in users
            //        .First(x => x.Id == subscribtion.SubscribedAuthorId)
            //            .Content)
            //    {
            //        allContents.Add(article);
            //    }
            //}

            //foreach (var tag in user.IgnoredTags)
            //{
            //    allContents = allContents
            //            .Where(article => !article.Tags
            //                .Any(articleTag => articleTag.TagId == tag.TagId))
            //                    .ToList();
            //}

            var ordered = feedContents.OrderByDescending(x => x.Date).Take(100);
            List<UserTextContent> result = new List<UserTextContent>();
            
            for (int i = (page - 1) * 10; i < ordered.Count() && i < page * 10; ++i)
            {
                result.Add(ordered.ElementAt(i));
            }

            ViewBag.currentPage = page;
            ViewBag.pagesCount = (int)Math.Ceiling((float)allContents.Count / 10.0);
            if (result.Count == 0)
            {
                ViewBag.currentPage = -1;
            }
            return View(result);
        }

        public ActionResult Search(int page, int[] tags, int[] ignoredTags, string title, string order = "date")
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();

            //List<Article> articles = (from content in applicationContext.Contents
            //                          where content is Article
            //                          select content as Article).ToList();
            List<UserTextContent> articles = applicationContext.Contents.ToList();
            
            if (tags != null)
            {

                foreach (int tagId in tags)
                {
                    articles = articles
                        .Where(article => article.Tags
                            .Any(articleTag => articleTag.TagId == tagId))
                                .ToList();
                }
                ViewBag.SelectedTags = applicationContext.Tags.Where(x => tags.Contains(x.Id)).ToList();
            }
            else
            {
                ViewBag.SelectedTags = new List<Tag>();
            }

            if (ignoredTags != null)
            {

                foreach (int tagId in ignoredTags)
                {
                    articles = articles
                        .Where(article => !article.Tags
                            .Any(articleTag => articleTag.TagId == tagId))
                                .ToList();
                }
                ViewBag.IgnoredTags = applicationContext.Tags.Where(x => ignoredTags.Contains(x.Id)).ToList();
            }
            else
            {
                ViewBag.IgnoredTags = new List<Tag>();
            }

            if (!string.IsNullOrEmpty(title))
            {
                articles = articles.Where(article => article
                    .Title.ToLower().Contains(title.ToLower())).ToList();
            }

            if (ignoredTags == null)
                tags = new int[0];
            if (tags == null)
                ignoredTags = new int[0];
            ViewBag.ArticleTitle = title ?? "";
            List<UserTextContent> result = new List<UserTextContent>();
            ViewBag.pagesCount = (int)Math.Ceiling((float)articles.Count / 10.0);
            ViewBag.currentPage = page;
            ViewBag.Tags = tags;
            ViewBag.AllTags = applicationContext.Tags.ToList();

            if (order == "date")
            {
                ViewBag.Order = "date";
                articles = articles.OrderByDescending(x => x.Date).ToList();
            }
            else
            {
                ViewBag.Order = "rating";
                articles = articles.OrderByDescending(x => x.Rating).ToList();
            }

            for (int i = (page - 1) * 10; i < articles.Count && i < page * 10; ++i)
            {
                result.Add(articles[i]);
            }
            if (result.Count == 0)
            {
                ViewBag.currentPage = -1;
            }

            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUser = applicationContext.Users.FirstOrDefault(user => user.UserName == User.Identity.Name);
            }

            ViewBag.NeedSidebar = true;

            return View(result);
        }

        public Dictionary<string, int> GetTagsCloudBlock(int maxTags = 20)
        {
            Dictionary<string, int> result = new Dictionary<string, int>();
            // Counts number of tags added (we only need max of %maxTags% tags).
            int count = 0;
            int total = maxTags < applicationContext.Tags.Count() ? maxTags : applicationContext.Tags.Count();
            ViewBag.Links = new Dictionary<string, int>();
            foreach (var tag in applicationContext.Tags
                        .OrderByDescending(x => x.ContentTags.Count))
            {
                result.Add(tag.Word, count * 5 / (total));
                ViewBag.Links.Add(tag.Word, tag.Id);
                ++count;
                if (count >= maxTags)
                    break;
            }
            return result;
        }
    }
}

Comicsbook/Views/Shared/CalendarPartial.cshtml
@using Comicsbook.Models

@{
    ApplicationUser currentUser = (ApplicationUser)ViewData["User"];
    int month = (int)ViewData["Month"];
    int year = (int)ViewData["Year"];

    string stringMonth = "";

    switch (month)
    {
        case 1:
            stringMonth = "January";
            break;
        case 2:
            stringMonth = "February";
            break;
        case 3:
            stringMonth = "March";
            break;
        case 4:
            stringMonth = "April";
            break;
        case 5:
            stringMonth = "May";
            break;
        case 6:
            stringMonth = "June";
            break;
        case 7:
            stringMonth = "July";
            break;
        case 8:
            stringMonth = "August";
            break;
        case 9:
            stringMonth = "September";
            break;
        case 10:
            stringMonth = "October";
            break;
        case 11:
            stringMonth = "November";
            break;
        default:
            stringMonth = "December";
            break;
    }  
    
    DateTime date = new DateTime(year, month, 1);
    DayOfWeek startDayOfWeek = date.DayOfWeek;
    DayOfWeek dayOfWeek = DayOfWeek.Monday;

    bool started = false;
    bool finished = false;

    int day = 1;
}
<div id="calendar" style="display:inline">
    
    <div style="float:left">
        @using (Ajax.BeginForm("ShowPartialCalendar", "Calendar", new AjaxOptions { UpdateTargetId = "calendar" }))
        {
            <input name="month" value="@(month > 1 ? month - 1 : 12)" type="hidden" />
            <input name="year" value="@(month == 1 ? year - 1 : year)" type="hidden" />
            <button name="submit" id="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-chevron-left" style="color:red;"></span>   
            </button>
        }
    </div>
    <div style="float:left; margin-left: 10px;">
        @using (Ajax.BeginForm("ShowPartialCalendar", "Calendar", new AjaxOptions { UpdateTargetId = "calendar" }))
        {
            <input name="month" value="@(month < 12 ? month + 1 : 1)" type="hidden" />
            <input name="year" value="@(month == 12 ? year + 1 : year)" type="hidden" />
            <button name="submit" id="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-chevron-right" style="color:red;"></span></button>
        }
    </div>
    <div style="margin-left: 10px; float:left;">
        <h4>@(stringMonth) @year</h4>
    </div>
    <table class="table-bordered" style="clear:left">
        <tr style="height:40px">
            <td width="100" style="text-align:center">Monday</td>
            <td width="100" style="text-align:center">Tuesday</td>
            <td width="100" style="text-align:center">Wednesday</td>
            <td width="100" style="text-align:center">Thursday</td>
            <td width="100" style="text-align:center">Friday</td>
            <td width="100" style="text-align:center">Saturday</td>
            <td width="100" style="text-align:center">Sunday</td>
        </tr>
        @while (!finished)
        {
            <tr style="height:70px">
                @for (int i = 0; i < 7; i++)
                {
                    switch (i)
                    {
                        case 0:
                            dayOfWeek = DayOfWeek.Monday;
                            break;
                        case 1:
                            dayOfWeek = DayOfWeek.Tuesday;
                            break;
                        case 2:
                            dayOfWeek = DayOfWeek.Wednesday;
                            break;
                        case 3:
                            dayOfWeek = DayOfWeek.Thursday;
                            break;
                        case 4:
                            dayOfWeek = DayOfWeek.Friday;
                            break;
                        case 5:
                            dayOfWeek = DayOfWeek.Saturday;
                            break;
                        case 6:
                            dayOfWeek = DayOfWeek.Sunday;
                            break;
                    }
                    if (started)
                    {
                        if (finished)
                        {
                            <td style="background-color: gray"> </td>
                        }
                        else
                        {
                            List<SubscribedEvent> currentDayEvents = currentUser.SubscribedEvents.Where(se => se.Event.EventDate.Value.Year == year && se.Event.EventDate.Value.Month == month && se.Event.EventDate.Value.Day == day).ToList();
                            List<SubscribedMeeting> currentDayMeetings = currentUser.SubscribedMeetings.Where(sm => sm.Meeting.EventDate.Value.Year == year && sm.Meeting.EventDate.Value.Month == month && sm.Meeting.EventDate.Value.Day == day).ToList();
                            int totalCount = currentDayEvents.Count + currentDayMeetings.Count;

                            if (day < DateTime.DaysInMonth(year, month))
                            {
                                <td>
                                    <div>@day</div>
                                    @if (totalCount == 1)
                                    {
                                        if (currentDayEvents.Count == 1)
                                        {
                                            @Html.ActionLink(currentDayEvents[0].Event.Title, "Show", "UserContent", new { id = currentDayEvents[0].EventId }, null)
                                        }
                                        else
                                        {
                                            @Html.ActionLink(currentDayMeetings[0].Meeting.Title, "Show", "UserContent", new { id = currentDayMeetings[0].MeetingId }, null)
                                        }
                                    }
                                    else if (totalCount > 1)
                                    {
                                        <div class="dropdown" style="display:inline;">
                                            <a class="dropdown-toggle" data-toggle="dropdown" style="cursor:pointer; margin:4px">
                                                @totalCount Events
                                            </a>
                                            <ul class="dropdown-menu">
                                                @for (int k = 0; k < currentDayEvents.Count; k++)
                                                {
                                                    <li>@Html.ActionLink(currentDayEvents[k].Event.Title, "Show", "UserContent", new { id = currentDayEvents[k].EventId }, null)</li>
                                                }
                                                @if (currentDayMeetings.Count > 0 && currentDayEvents.Count > 0)
                                                {
                                                    <li class="divider"></li>
                                                }
                                                @for (int k = 0; k < currentDayMeetings.Count; k++)
                                                {
                                                    <li>@Html.ActionLink(currentDayMeetings[k].Meeting.Title, "Show", "UserContent", new { id = currentDayMeetings[k].MeetingId }, null)</li>
                                                }
                                            </ul>
                                        </div>
                                    }
                                </td>
                                    { day++; }
                            }
                            else
                            {
                                <td>
                                    <div>@day</div>
                                </td>
                                {
                                    day++;
                                    finished = true;
                                }
                            }
                        }
                    }
                    else
                    {
                        if (startDayOfWeek == dayOfWeek)
                        {
                            <td>
                                <div>@day</div>
                            </td>
                            {
                                day++;
                                started = true;
                            }
                        }
                        else
                        {
                            <td style="background-color: gray"> </td>
                        }
                    }
                }
            </tr>
        }
    </table>
</div>

Comicsbook/Views/Shared/TagListMenuPartial.cshtml
@model Comicsbook.Models.UserTextContent
@using Comicsbook.Models

@{
    ApplicationUser currentUser = (ApplicationUser)ViewData["CurrentUser"];

    var contentId = ViewData["ContentId"];
}

<span id="tagMenu">
    @foreach (var tag in Model.Tags)
    {
        <div class="dropdown" style="display:inline;">
            <span data-toggle="dropdown" class="label label-info btn-xs" style="cursor:pointer; margin:4px">
                @tag.Tag.Word
            </span>
            <ul class="dropdown-menu">
                <li style="height: 25px">
                    <button class="btn btn-default" style="width:100%; height:25px; border:none; font-size:12px; text-align: left;" onclick="location.href='/Feed/Search?tags=@(tag.Tag.Id)&page=1'">Search</button>
                    @*@Html.ActionLink("Search", "Search", "Feed",
                            new { tags = tag.Tag.Id, page = 1 }, null)*@
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li style="height: 25px">
                        @using (Ajax.BeginForm("SubscribeAtTag", "UserContent", new AjaxOptions { UpdateTargetId = "tagMenu" }))
                        {
                            <input name="tagId" type="hidden" value="@tag.Tag.Id" />
                            <input name="contentId" type="hidden" value="@contentId" />
                            <button name="submit" id="submit" class="btn btn-default" style="width:100%; height:25px; border:none; text-align: left; font-size:12px;">
                                Subscribe
                                @if (currentUser != null && currentUser.SubscribedTags.Count(t => t.TagId == tag.Tag.Id) > 0)
                                {
                                    <img src="~/Pictures/tick.png" style="position: relative; left:50px; width:15px; height: 15px;" />
                                }
                                else
                                {
                                    <img src="~/Pictures/tick 2.png" style="position: relative; left:50px; width:15px; height: 15px;" />
                                }
                            </button>
                        }
                    </li>
                    <li style="height: 25px">
                        @using (Ajax.BeginForm("IgnoreTag", "UserContent", new AjaxOptions { UpdateTargetId = "tagMenu" }))
                        {
                            <input name="tagId" type="hidden" value="@tag.Tag.Id" />
                            <input name="contentId" type="hidden" value="@contentId" />
                            <button name="submit" id="submit" class="btn btn-default" style="width:100%; height:25px; border:none; display:inline; text-align: left; font-size:12px;">
                                Ignore
                                @if (currentUser != null && currentUser.IgnoredTags.Count(t => t.TagId == tag.Tag.Id) > 0)
                                {
                                    <img src="~/Pictures/tick.png" style="position: relative; left:70px;  width:15px; height: 15px;" />
                                }
                                else
                                {
                                    <img src="~/Pictures/tick 2.png" style="position: relative; left:70px; width:15px; height: 15px;" />
                                }
                            </button>
                        }
                    </li>
                }
            </ul>
        </div>
    }
</span>

Comicsbook/Views/Shared/TagsBlock.cshtml
@{
    ViewBag.Title = "Tags";
    Dictionary<string, int> res = new Dictionary<string,int>();
}
<div id="cloud">
    @{
        foreach (var t in ViewBag.TagsCloudBlock)
        {
            res.Add(t.Key, t.Value);
        }
    }
    @foreach (var item in res.OrderBy(x => x.Key))
    {
        <span style="font-size:@(165 - 20 * item.Value)%">
            @Html.ActionLink(item.Key, "Search", "Feed",
                 new { page = 1, tags = ViewBag.Links[item.Key] },
                  new { @class = "label label-info btn-xs" })
        </span>
    }
</div>

Comicsbook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Pictures/favicon.ico" type="image/png">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog login-modal" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Login</h4>
                </div>
                <div class="modal-body">
                    <img id="profile-img" class="profile-img-card" src="@Url.Content("~/Pictures/avatar_anon.png")" />
                    <form action="@Url.Action("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl })" method="post" class="form-signin">
                        @Html.AntiForgeryToken()
                        <span id="reauth-email" class="reauth-email"></span>
                        <input class="form-control" data-val="true" data-val-minlength="At least 4 characters" data-val-minlength-min="4" data-val-required="Login required" id="Login" name="Login" type="text" placeholder="Login" required autofocus>
                        <span class="field-validation-valid text-danger" data-valmsg-for="Login" data-valmsg-replace="true"></span>
                        <input class="form-control" data-val="true" data-val-required="Password required" id="Password" name="Password" type="password" placeholder="Password" required>
                        <span class="field-validation-valid text-danger" data-valmsg-for="Password" data-valmsg-replace="true"></span>
                        <div id="remember" class="checkbox">
                            <label>
                                <input data-val="true" data-val-required="Remember me?" id="RememberMe" name="RememberMe" type="checkbox" value="true" /><input name="RememberMe" type="hidden" value="false" /> Remember me
                            </label>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Log in</button>
                    </form>
                    @*<a href="#" class="forgot-password">
                        Forgot the password?
                    </a>*@
                    <hr />
                    @Html.Partial("_SocialButtons", new Comicsbook.Models.ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
                </div>
            </div>
        </div>
    </div>

    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Home", "Feed", "Feed", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Articles", "Articles", "UserContent")</li>
                    <li>@Html.ActionLink("Events", "Events", "UserContent")</li>
                    <li>@Html.ActionLink("Meetings", "Meetings", "UserContent")</li>
                    <li>@Html.ActionLink("Tags", "TagsCloud", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Calendar", "ShowInitialCalendar", "Calendar")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>
    <div class="container body-content">
        @{ if (ViewBag.NeedSidebar != null)
            {
                <div class="row">
                    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                        @RenderBody()
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.Partial("_Sidebar")
                    </div>
                </div>
            }
            else
            {
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @RenderBody()
                    </div>
                </div>
            }
        }
    </div>
    <div class="container">
        <div id="footer" class="navbar navbar-default navbar-static-bottom footer">
            <p class="navbar-text pull-left footer">
                © 2015 - Multiverse
            </p>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Comicsbook/Views/Shared/_ProfileBlock.cshtml
@using Comicsbook.Models;
<div class="profile-sidebar panel panel-body">
    <div class="profile-userpic">
        <img src="@ViewBag.CurrentUser.Userpic.Image" class="img-responsive" alt="@ViewBag.CurrentUser.Name">
    </div>
    <div class="profile-usertitle">
        <div class="profile-usertitle-name">
            @ViewBag.CurrentUser.UserName
        </div>
    </div>
    <div class="profile-usermenu">
        <ul class="nav">
            <li>
                <a href="@Url.Action("Users", "Account", new { id = User.Identity.Name.ToString() })">
                    <i class="glyphicon glyphicon-user"></i>
                    Profile
                </a>
            </li>
            <li>
                <a href="@Url.Action("ShowInitialCalendar", "Calendar", null)">
                    <i class="glyphicon glyphicon-calendar"></i>
                    Calendar
                </a>
            </li>
            <li>
                <a href="@Url.Action("New", "UserContent", new { type = Comicsbook.Models.ContentType.Article })">
                    <i class="glyphicon glyphicon-pencil"></i>
                    New article
                </a>
            </li>
            <li>
                <a href="@Url.Action("New", "UserContent", new { type = Comicsbook.Models.ContentType.Event })">
                    <i class="glyphicon glyphicon-bullhorn"></i>
                    New event
                </a>
            </li>
            <li>
                <a href="@Url.Action("New", "UserContent", new { type = Comicsbook.Models.ContentType.Meeting })">
                    <i class="glyphicon glyphicon-flag"></i>
                    New meeting
                </a>
            </li>
        </ul>
    </div>
    @{
        ApplicationDbContext context = new ApplicationDbContext();
        ApplicationUser currentUser = context.Users.First(user => user.UserName == User.Identity.Name);
        List<SubscribedEvent> currentDayEvents = currentUser.SubscribedEvents.Where(se => se.Event.EventDate.Value.Year == DateTime.Now.Year && (se.Event.EventDate.Value.DayOfYear == DateTime.Now.DayOfYear || se.Event.EventDate.Value.DayOfYear == DateTime.Now.DayOfYear + 1)).ToList();
        List<SubscribedMeeting> currentDayMeetings = currentUser.SubscribedMeetings.Where(sm => sm.Meeting.EventDate.Value.Year == DateTime.Now.Year && (sm.Meeting.EventDate.Value.DayOfYear == DateTime.Now.DayOfYear || sm.Meeting.EventDate.Value.DayOfYear == DateTime.Now.DayOfYear + 1)).ToList();
        if (currentDayEvents.Count() > 0 || currentDayMeetings.Count() > 0)
        {
            <div class="alert alert-info alert-dismissable" role="alert" style="margin-bottom: -10px;">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                @Html.Partial("UpcomingEvents")
            </div>
        }
    }
</div>