Comicsbook/Models/Article.cs
namespace Comicsbook.Models
{
    public class Article : UserTextContent
    {
        public Article() : base()
        {
            
        }
    }
}

Comicsbook/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Comicsbook.Models
{
    public class Event : UserTextContent
    {
        public Event() : base()
        {
            SubscribedEvents = new List<SubscribedEvent>();
        }

        [Column]
        //[Required(ErrorMessage="Specify the date of event.")]
        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        //[Display(Name = "Date of event")]
        public DateTime? EventDate { get; set; }

        public virtual ICollection<SubscribedEvent> SubscribedEvents { set; get; }
    }

    public class SubscribedEvent
    {
        [Key, Column(Order = 1)]
        [ForeignKey("User")]
        public string UserId { set; get; }
        public virtual ApplicationUser User { set; get; }

        [Key, Column(Order = 2)]
        [ForeignKey("Event")]
        public int EventId { set; get; }
        public virtual Event Event { set; get; }
    }
}

Comicsbook/Models/Meeting.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Comicsbook.Models
{
    public class Meeting: Event
    {
        public Meeting(): base()
        {
            SubscribedMeetings = new List<SubscribedMeeting>();
        }

        /// <summary>
        /// Долгота места проведения - для карт Google.
        /// </summary>
        [Column]
        //[Required(ErrorMessage = "Put the place of meeting at the map.")]
        public string GeoLong { get; set; }

        /// <summary>
        /// Широта места проведения - для карт Google.
        /// </summary>
        [Column]
        //[Required(ErrorMessage="Put the place of meeting at the map.")]
        public string GeoLat { get; set; }

        public virtual ICollection<SubscribedMeeting> SubscribedMeetings { set; get; }
    }

    public class SubscribedMeeting
    {
        [Key, Column(Order = 1)]
        [ForeignKey("User")]
        public string UserId { set; get; }
        public virtual ApplicationUser User { set; get; }

        [Key, Column(Order = 2)]
        [ForeignKey("Meeting")]
        public int MeetingId { set; get; }
        public virtual Meeting Meeting { set; get; }
    }
}

Comicsbook/Controllers/UserContentController.cs
using Comicsbook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Comicsbook.Controllers
{
    [HandleError()]
    public class UserContentController : Controller
    {
        ApplicationDbContext applicationContext = new ApplicationDbContext();

        [HttpGet]
        public ActionResult Index()
        {
            //List<Article> articles = new List<Article>();
            //lock (applicationContext.locker)
            //{
            //    articles = applicationContext.Articles.ToList();
            //    ViewBag.Users = applicationContext.Users.ToList();
            //}

            //return View(articles);

            ///for future - RedirectToAction("Index", "Feed", ...)

            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            return new EmptyResult();
        }

        public ActionResult Articles()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUser = applicationContext.Users.FirstOrDefault(user => user.UserName == User.Identity.Name);
            }

            ViewBag.NeedSidebar = true;
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            return View(applicationContext.Articles.ToList().OrderByDescending(x => x.Date));
        }

        public ActionResult Events()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUser = applicationContext.Users.FirstOrDefault(user => user.UserName == User.Identity.Name);
            }

            ViewBag.NeedSidebar = true;
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            return View(applicationContext.Events.ToList().OrderByDescending(x => x.Date));
        }

        public ActionResult Meetings()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUser = applicationContext.Users.FirstOrDefault(user => user.UserName == User.Identity.Name);
            }

            ViewBag.NeedSidebar = true;
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            return View(applicationContext.Meetings.ToList().OrderByDescending(x => x.Date));
        }

        [ActionName("article")]
        public ActionResult Article(int id)
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            return RedirectToAction("Show", new { id = id });
        }

        [ActionName("event")]
        public ActionResult Event(int id)
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            return RedirectToAction("Show", new { id = id });
        }

        [ActionName("meeting")]
        public ActionResult Meeting(int id)
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            return RedirectToAction("Show", new { id = id });
        }

        [AllowAnonymous]
        public ActionResult Show(int id)
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            ApplicationUser currentUser = applicationContext.Users.FirstOrDefault(user => user.UserName == User.Identity.Name);
            var selected = applicationContext.Contents.FirstOrDefault(content => content.Id == id);

            if (selected == null)
            {
                return new HttpNotFoundResult();
            }

            ViewBag.Type = selected.Type;

            ViewBag.NeedSidebar = true;

            selected.Comments = applicationContext.Comments.Where(comment => comment.ContentId == id).ToList();

            ViewBag.Comments = applicationContext.Comments.Where(comment => comment.ContentId == id).ToList();
            ViewBag.Users = applicationContext.Users.ToList();
            ViewBag.CurrentUser = currentUser;
            return View(selected);
        }


        [NonAction]
        private List<Tag> GetTags()
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            // Сортировка тегов по количеству их упоминаний в статьях.
            List<Tag> tags = new List<Tag>();
            List<Tag> existingTags = applicationContext.Tags.ToList();

            while (existingTags.Count() > 0)
            {
                // Нахождение максисального элемента.
                Tag maxTag = existingTags.ElementAt(0);
                for (int i = 1; i < existingTags.Count(); i++)
                {
                    Tag existingTag = existingTags.ElementAt(i);
                    if (existingTag.ContentTags.Count > maxTag.ContentTags.Count)
                    {
                        maxTag = existingTag;
                    }
                }
                // Добавление максимального элемента в новую последовательность.
                tags.Add(maxTag);
                // Удаление элемента из старой последовательности.
                existingTags.Remove(maxTag);
            }
            return tags;
        }


        [Authorize]
        public ActionResult New(ContentType type)
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUser = applicationContext.Users.FirstOrDefault(user => user.UserName == User.Identity.Name);
            }

            ViewBag.NeedSidebar = true;
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            ViewBag.Tags = GetTags();
            ViewBag.NewType = type;
            return View();
        }

        //[ValidateInput(false)]
        [Authorize]
        [HttpPost]
        public ActionResult New(string Title, string Text, string[] tags, string longtitude = "", string lattitude = "", DateTime? eventDate = null,
            ContentType type = ContentType.Article)
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            string authorId = applicationContext.Users.First(user => user.UserName == User.Identity.Name).Id;
            UserTextContent content = null;
            if (type == ContentType.Article)
            {
                content = new Article()
                {
                    Date = DateTime.Now,
                    AuthorId = authorId,
                    Title = Title,
                    Text = Text,
                };
            }
            if (type == ContentType.Event)
            {
                content = new Event()
                {
                    Date = DateTime.Now,
                    AuthorId = authorId,
                    Title = Title,
                    Text = Text,
                    EventDate = eventDate
                };
            }
            if (type == ContentType.Meeting)
            {
                content = new Meeting()
                {
                    Date = DateTime.Now,
                    AuthorId = authorId,
                    Title = Title,
                    Text = Text,
                    EventDate = eventDate,
                    GeoLong = longtitude,
                    GeoLat = lattitude
                };
            }

            if (content == null)
            {
                return new EmptyResult();
            }

            if (Title != string.Empty && Text != string.Empty && ModelState.IsValid)
            {
                if (tags == null)
                {
                    tags = new string[0];
                }

                // Добавляем теги
                for (int i = 0; i < tags.Length; i++)
                {
                    string word = tags[i];
                    Tag existingTag = applicationContext.Tags.FirstOrDefault(tag => tag.Word == word);
                    if (existingTag != null && existingTag.Word != "" && existingTag.Word != null)
                    {
                        ContentTag newContentTag = new ContentTag();
                        newContentTag.Content = content;
                        newContentTag.Tag = existingTag;
                        applicationContext.ContentTags.Add(newContentTag);

                        content.Tags.Add(newContentTag);
                    }
                    else
                    {
                        ContentTag newContentTag = new ContentTag();
                        newContentTag.Content = content;

                        Tag newTag = new Tag();
                        newTag.Id = applicationContext.Tags.Count() + 1;
                        newTag.Word = tags[i];
                        newTag.ContentTags.Add(newContentTag);

                        newContentTag.Tag = newTag;

                        content.Tags.Add(newContentTag);

                        applicationContext.Tags.Add(newTag);
                        applicationContext.ContentTags.Add(newContentTag);
                    }
                }

                applicationContext.Contents.Add(content);
                applicationContext.SaveChanges();
                int tempId = content.Id;
                return RedirectToAction("Show", new { id = tempId });
            }
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            ViewBag.Tags = GetTags();
            ViewBag.NewType = type;
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUser = applicationContext.Users.FirstOrDefault(user => user.UserName == User.Identity.Name);
            }

            ViewBag.NeedSidebar = true;
            return View(content);
        }

        [ValidateInput(false)]
        public ActionResult Edit(UserTextContent content)
        {
            ViewBag.TagsCloudBlock = GetTagsCloudBlock();
            string id = Request.Form.Get("id") ?? content.Id.ToString();
            UserTextContent editedContent = applicationContext.Contents.FirstOrDefault(
                edited => edited.Id.ToString() == id);
            if (editedContent == null)
            {
                return new EmptyResult();
            }
            //string newText = Request.Form.Get("Text");
            string newText = null;
            if (content != null)
            {
                newText = content.Text;
            }

Comicsbook/Views/UserContent/AddComment.cshtml
@model Comicsbook.Models.Comment
@{
    AjaxOptions options = new AjaxOptions
    {
        UpdateTargetId = "commentsContainer",
        Url = Url.Action("AddComment"),
        InsertionMode = InsertionMode.InsertAfter,
        OnSuccess = "finishCommenting"
    };
}

@using (Ajax.BeginForm(options))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">@User.Identity.Name</h3>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.CommentText, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your comment..." } })
                    @Html.ValidationMessageFor(model => model.CommentText, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @Html.HiddenFor(model => model.CommentAnswerId)
        @Html.HiddenFor(model => model.ContentId)

        <div id="addCommentButtons" class="hidden">
            <div class="panel-footer">
                <div class="label label-default hidden pull-left" id="replyLabel">
                    Reply to comment #
                </div>

                <div class="pull-right">
                    <div class="btn btn-default" id="cancelComment" name="cancelComment">
                        Cancel
                    </div>
                    <input class="btn btn-primary" id="commentButton" name="commentButton" type="submit" value="Comment" />
                </div>
                <br />
                <br />
            </div>
        </div>
    </div>
}

Comicsbook/Views/UserContent/Articles.cshtml
@model IEnumerable<Comicsbook.Models.Article>

@{
    ViewBag.Title = "Articles";
    //ViewBag.Type = Comicsbook.Models.ContentType.Article;
}

@*
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("New article", "New", "UserContent", 
        new { type = Comicsbook.Models.ContentType.Article }, 
        new { @class = "btn btn-primary"})
}
*@

@Html.Partial("ArticleList", Model)

Comicsbook/Views/UserContent/CreateCommentRating.cshtml
@model Comicsbook.Models.Comment
@using Comicsbook.Models

@{
    string thumbsUp = "fa fa-thumbs-up fa-lg";
    string thumbsDown = "fa fa-thumbs-down fa-lg";
    string likeUpClasses = thumbsUp + " like";
    string likeDownClasses = thumbsDown + " like";
    string onClickAction = "AddCommentMark";
    string markClassName;

    if (ViewBag.CommentLike != null)
    {
        if (ViewBag.CommentLike)
        {
            likeUpClasses = thumbsUp + " " + "liked-up";
            likeDownClasses = thumbsDown;
        }
        else
        {
            likeDownClasses = thumbsDown + " " + "liked-down";
            likeUpClasses = thumbsUp;
        }
    }
    else if (Model.Author.UserName != User.Identity.Name)
    {
        likeUpClasses += " " + "like-up";
        likeDownClasses += " " + "like-down";
    }
}

@if (User.Identity.IsAuthenticated && ViewBag.CommentLike == null && Model.Author.UserName != User.Identity.Name)
{
    @Ajax.ActionLink(" ", onClickAction,
    routeValues: new
    {
        mark = MarkValue.Like,
        commentId = Model.Id
    },
    ajaxOptions: new AjaxOptions
    {
        UpdateTargetId = "ratingDiv" + Model.Id,
        //Url = Url.Action("AddMark", new { isLike = true })
    },
    htmlAttributes: new
    {
        @class = likeUpClasses,
        id = "like"
    })

    @Ajax.ActionLink(" ", onClickAction,
        routeValues: new
        {
            mark = MarkValue.Dislike,
            commentId = Model.Id
        },
        ajaxOptions: new AjaxOptions
        {
            UpdateTargetId = "ratingDiv" + Model.Id,
            //Url = Url.Action("AddMark", new { isLike = false })
        },
        htmlAttributes: new
        {
            @class = likeDownClasses,
            id = "dislike"
        })
}
else
{
    TagBuilder builder = new TagBuilder("i");
    builder.Attributes.Add("class", likeUpClasses);
    @MvcHtmlString.Create(builder.ToString())

    builder = new TagBuilder("i");
    builder.Attributes.Add("class", likeDownClasses);
    @MvcHtmlString.Create(builder.ToString())
}

@if (Model.Rating > 0)
{
    markClassName = "liked-up";
}
else if(Model.Rating < 0)
{
    markClassName = "liked-down";
}
else
{
    markClassName = "negative";
}

<strong class=@markClassName>@Model.Rating</strong>

Comicsbook/Views/UserContent/Edit.cshtml
@model Comicsbook.Models.UserTextContent
@using Comicsbook.Models

@{
    bool isCurrentUserArticle = (User.Identity.Name == Model.Author.UserName);
    AjaxOptions ajaxOptions = new AjaxOptions
    {
        UpdateTargetId = "contentBlock",
        Url = Url.Action("Edit"),
        OnSuccess = "endEditing"
    };
}

<div class="show" id="contentText" name="contentText">
    @MvcHtmlString.Create(BBCodeTags.ToHtml(UserTextContent.Show(Model)).ToString().Replace("\r\n", "<br />"))
</div>
@if (isCurrentUserArticle)
{
    <div class="sr-only" id="editBlock" name="editBlock">
        @using (Ajax.BeginForm(ajaxOptions))
        {
            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            <div style="margin-top:10px">
                <div class="btn btn-default" id="cancelChanges" name="cancelChanges">
                    Cancel
                </div>
                <input class="btn btn-primary" id="saveChanges" name="saveChanges" type="submit" value="Save" />
            </div>
            @Html.HiddenFor(article => article.Id)
        }
    </div>
}

Comicsbook/Views/UserContent/Events.cshtml
@model IEnumerable<Comicsbook.Models.Event>

@{
    ViewBag.Title = "Events";
    //ViewBag.Type = Comicsbook.Models.ContentType.Event;
}
@*
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("New event", "New", "UserContent",
        new { type = Comicsbook.Models.ContentType.Event },
        new { @class = "btn btn-primary" })
}
*@

@Html.Partial("ArticleList", Model)

Comicsbook/Views/UserContent/Index.cshtml
@model IEnumerable<Comicsbook.Models.Article>
@using Comicsbook.Models

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.Partial("ArticleList", Model)

Comicsbook/Views/UserContent/Meetings.cshtml
@model IEnumerable<Comicsbook.Models.Meeting>

@{
    ViewBag.Title = "Meetings";

    //ViewBag.Type = Comicsbook.Models.ContentType.Meeting;
}

@*
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("New meeting", "New", "UserContent",
        new { type = Comicsbook.Models.ContentType.Meeting },
        new { @class = "btn btn-primary" })
}
*@

@Html.Partial("ArticleList", Model)

Comicsbook/Views/UserContent/New.cshtml
@model Comicsbook.Models.UserTextContent
@using Comicsbook.Models;


@{
    string title = "New " + ViewBag.NewType.ToString();
    ViewBag.Title = title;
    List<Tag> tags = ViewBag.Tags;
    string tagWord = string.Empty;
}
@for (int i = 0; i < tags.Count; ++i)
{
    {
        tagWord = tags[i].Word + "," + tags[i].Id;
    }
    <input type="hidden" id="tagWord @i" value="@tagWord" />
}
<div class="well">
@*DON'T REMOVE THIS HIDDEN INPUT!!!1111*@
<input type="hidden" id="newIgnoredTag" value="dummy" />
<h2>@title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", required = "true" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="hidden" id="tags-input-mode" value="add" />
        <div class="form-group">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                <div id="selectedTags"></div>
                <br />
                <div class="dropdown">
                    <input type="text" id="newTag" data-toggle="dropdown" class="form-control" autocomplete="off" placeholder="Confirm tag by pressing Enter">
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" id="tagList"></ul>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">Use these tools to decorate your text:</div>
                    <div class="panel-body">
                        <span class="text-decor">
                            @*<img src="~/Pictures/Text Decorations/bold.png" id="b" title="Bold">
                                <img src="~/Pictures/Text Decorations/italic.png" id="i" title="Italic">
                                <img src="~/Pictures/Text Decorations/underlined.png" id="u" title="Underlined">
                                <img src="~/Pictures/Text Decorations/strike.png" id="s" title="Strike">
                                <img src="~/Pictures/Text Decorations/image.png" id="img" title="Image">
                                <img src="~/Pictures/Text Decorations/youtube.png" id="video" title="Video">
                                <img src="~/Pictures/Text Decorations/url.png" id="url" title="Link">
                                <img src="~/Pictures/Text Decorations/quote.png" id="quote" title="Quote">*@

                            <i class="fa fa-bold fa-2x text-decor-img fa-border" id="b" title="Bold"></i>
                            <i class="fa fa-italic fa-2x text-decor-img fa-border" id="i" title="Italic"></i>
                            <i class="fa fa-underline fa-2x text-decor-img fa-border" id="u" title="Underlined"></i>
                            <i class="fa fa-strikethrough fa-2x text-decor-img fa-border" id="s" title="Strike"></i>
                            <i class="fa fa-image fa-2x text-decor-img fa-border" id="img" title="Image"></i>
                            <i class="fa fa-youtube-square fa-2x text-decor-img fa-border" id="video" title="Video"></i>
                            <i class="fa fa-link fa-2x text-decor-img fa-border" id="url" title="Link"></i>
                            <i class="fa fa-quote-left fa-2x text-decor-img fa-border" id="quote" title="Quote"></i>
                        </span>
                    </div>
                </div>
                <div>
                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control", id = "textbox", required = "true" } })
                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @if (ViewBag.NewType == Comicsbook.Models.ContentType.Event
                || ViewBag.NewType == Comicsbook.Models.ContentType.Meeting)
        {
            <div class="form-group">
                <label class="control-label col-md-2" for="eventDate">Date</label>
                <div class="col-md-4">
                    <input type="date" name="eventDate" id="eventDate" value="" class="form-control text-box single-line" required
                           min=@DateTime.Now.ToString("yyyy-MM-dd") max="2050-01-01" />
                </div>
            </div>
        }

        @if (ViewBag.NewType == Comicsbook.Models.ContentType.Meeting)
        {
            <div class="form-group">
                <label class="control-label col-md-2" for="eventDate">Place</label>
                <div class="col-md-4">
                    <div id="canvas" style="height: 600px; width:600px;"></div>
                    <input type="hidden" id="longtitude" name="longtitude" value="" required/>
                    <input type="hidden" id="lattitude" name="lattitude" value="" required />
                </div>
            </div>
        }
        @Html.HiddenFor(model => model.AuthorId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
</div>

@section scripts
{
    <script src="~/Scripts/Custom Scripts/TagsEnter.js"></script>

    <script src="~/Scripts/Custom Scripts/TextDecor.js"></script>
}

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="https://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
    <script type="text/javascript">

        var marker;
        var map;

        $(document).ready(function () {
            CreateValidationMessages();
            GetMap();
        });

        // Функция загрузки
        function GetMap() {

            google.maps.visualRefresh = true;

            navigator.geolocation.getCurrentPosition(function (p) {
                var LatLng = new google.maps.LatLng(p.coords.latitude, p.coords.longitude);
                var mapOptions = {
                    zoom: 15,
                    center: LatLng,
                    mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
                };
                map = new google.maps.Map(document.getElementById("canvas"), mapOptions);

                google.maps.event.addListener(map, 'click', function (event) {
                    if (marker == null)
                        addMarker(event.latLng);
                });//добавляем событие нажание мышки


            });

            function addMarker(location) {

                var myLatlng = new google.maps.LatLng(location.lat(), location.lng());

                marker = new google.maps.Marker({
                    position: myLatlng,
                    map: map,
                    draggable: true
                });//добавление маркера

                document.getElementById("longtitude").value = location.lat();
                document.getElementById("lattitude").value = location.lng();

                google.maps.event.addListener(marker, "drag", function (event) {
                    document.getElementById("longtitude").value = event.latLng.lat();
                    document.getElementById("lattitude").value = event.latLng.lng();
                });
                
                // Берем для маркера иконку с сайта google
                marker.setIcon('http://maps.google.com/mapfiles/ms/icons/red-dot.png')
            }
        }

        // Настройка сообщений валидации.
        function CreateValidationMessages()
        {
            var titleInput = document.getElementById("Title");
            titleInput.oninvalid = function (e) {
                e.target.setCustomValidity("");
                if (!e.target.validity.valid) {
                    e.target.setCustomValidity("The field 'Title' is required.");
                }
            };
            titleInput.oninput = function (e) {
                e.target.setCustomValidity("");
            };

            var textInput = document.getElementById("textbox");
            textInput.oninvalid = function (e) {
                e.target.setCustomValidity("");
                if (!e.target.validity.valid) {
                    e.target.setCustomValidity("The field 'Text' is required.");
                }
            };
            textInput.oninput = function (e) {
                e.target.setCustomValidity("");
            };

            var dateInput = document.getElementById("eventDate");
            dateInput.oninvalid = function (e) {
                e.target.setCustomValidity("");
                if (!e.target.validity.valid) {
                    e.target.setCustomValidity("The field 'Event Date' is required.");
                }
            };
            dateInput.oninput = function (e) {
                e.target.setCustomValidity("");
            };

            var place = document.getElementById("longtitude");
            place.oninvalid = function (e) {
                e.target.setCustomValidity("");
                if (!e.target.validity.valid || e.target.value == "") {
                    e.target.setCustomValidity("The place of meeting is required.");
                }
            };
            place.oninput = function (e) {
                e.target.setCustomValidity("");
            };
        }
    </script>